version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          FIREFOX_BINARY: /home/circleci/checkout/firefox/firefox-bin

    working_directory: ~/checkout

    steps:
      - checkout

      # Download and cache dependencies (update the cache keys to force a newer version of devedition)
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}-devedition-20180608

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name:  Get devedition
          command: |
            if [ -d ./firefox ]; then
              echo "firefox dir exists, must be from cache"
            else
              ./node_modules/.bin/get-firefox -b devedition -p linux -e
            fi
            ls -l $FIREFOX_BINARY
            $FIREFOX_BINARY -v

      - save_cache:
          paths:
            - node_modules
            - firefox
          key: v1-dependencies-{{ checksum "package-lock.json" }}-devedition-20180608

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Build .XPI
          command: npm run build

      - run:
          name: Unit + functional tests
          command: npm run test

      - store_artifacts:
          path: "dist"

      - store_test_results:
          path: "test/coverage"
