version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          DISPLAY: :10
          FIREFOX_BINARY: /firefox/firefox

    working_directory: /shield-studies-addon-tempate

    steps:
      - run:
          name: xvfb and openbox
          command: Xvfb $DISPLAY -ac & sleep 1 & openbox
          background: true

      - checkout

      - run: npm install

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Build .XPI
          command: npm run build

      - run:
          name: Functional tests
          command: npm run test

      - store_artifacts:
          path: "dist"

      - store_artifacts:
          path: "artiacts"
