version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          FIREFOX_BINARY: /home/circleci/checkout/firefox/firefox-bin

    working_directory: ~/checkout

    steps:
      - checkout

      # Download and cache dependencies (update the cache keys to force a newer version of nightly)
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-nightly-20180425

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name:  Get nightly
          command: |
            if [ -d ./firefox ]; then
              echo "firefox dir exists, must be from cache"
            else
              ./node_modules/.bin/get-firefox -b nightly -p linux -e
            fi
            ls -l $FIREFOX_BINARY
            $FIREFOX_BINARY -v

      - save_cache:
          paths:
            - node_modules
            - firefox
          key: v1-dependencies-{{ checksum "package.json" }}-nightly-20180425

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Build .XPI
          command: npm run build

      #- run:
      #    name: Unit tests
      #    command: npm run test:karma

      - run:
          name: Functional tests
          command: npm run test:func

      - store_artifacts:
          path: "dist"

      #- store_test_results:
      #    path: "build/coverage"
